config/routes.rb
Rails.application.routes.draw do
  root 'portfolio#index'

  resource :portfolio, controller: :portfolio, only: [:show]

  controller :user do
    get 'summary'
  end

  devise_for :users

  devise_for :admin
  namespace :admin do
    resource :portfolio, controller: :portfolio, only: [:show, :update] do
      member do
        get 'growth'
        get 'transactions'
      end
    end

    resource :summaries, only: [:show] do
      member do
        get 'user/:user_id', action: 'user', as: 'user'
        get 'year/:year',    action: 'year', as: 'year'
      end
    end

    resources :investments, only: [:show] do
      member do
        get 'prices'
      end
    end

    resources :tax_docs, only: [:index, :show] do
      member do
        get 'form_1065'
        get 'schedule_d'
        get 'schedule_k'
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/admin/summaries_controller.rb
class Admin::SummariesController < Admin::BaseController
  def show
    @users = User.all
    # FIXME
    @years = [2013, 2014, 2015, 2016]
  end

  def user
    user = User.find(params[:user_id])
    @user_growths = UserYearGrowthPresenter.for_user(user)
    render 'user/summary'
  end

  def year
    year = params[:year].to_i
    @growths = UserYearGrowthPresenter.for_year(year)
  end
end

app/views/admin/summaries/show.html.haml
%ul
  - @users.each do |user|
    %li= link_to user.username, user_admin_summaries_path(user)

%ul
  - @years.each do |year|
    %li= link_to year, year_admin_summaries_path(year)

app/views/admin/summaries/year.html.haml
%table
  %thead
    %th User
    %th Starting Balance
    %th Contributions
    %th Reinvestments
    %th Gross Gains
    %th Management Fee
    %th Ending Balance
  %tbody
    - @growths.each do |growth|
      %tr
        %th= growth.user
        %td= number_to_currency growth.starting_value
        %td= number_to_currency growth.contribution_value
        %td= number_to_currency growth.reinvestment_value
        %td= number_to_currency growth.gross_gains
        - if growth.tentative?
          %td.tentative= number_to_currency -growth.estimated_fee
          %th.tentative= number_to_currency growth.tentative_value
        - else
          %td= number_to_currency -growth.booked_fee
          %th= number_to_currency growth.value
  %tfoot
    %tr
      %th
      %th= number_to_currency @growths.sum(&:starting_value)
      %th= number_to_currency @growths.sum(&:contribution_value)
      %th= number_to_currency @growths.sum(&:reinvestment_value)
      %th= number_to_currency @growths.sum(&:gross_gains)
      - if @growths.all?(&:tentative?)
        %th.tentative= number_to_currency -@growths.sum(&:estimated_fee)
        %th.tentative= number_to_currency @growths.sum(&:tentative_value)
      - else
        %td= number_to_currency -@growths.sum(&:booked_fee)
        %th= number_to_currency @growths.sum(&:value)