config/routes.rb
Rails.application.routes.draw do
  root 'portfolio#index'

  resource :portfolio, controller: :portfolio, only: [:show]

  controller :user do
    get 'summary'
  end

  devise_for :users

  devise_for :admin
  namespace :admin do
    resource :portfolio, controller: :portfolio, only: [:show, :update] do
      member do
        get 'growth'
        get 'transactions'
      end
    end

    resource :summaries, only: [:show] do
      member do
        get 'user/:user_id', action: 'user', as: 'user'
        get 'year/:year',    action: 'year', as: 'year'
      end
    end

    resources :investments, only: [:show] do
      member do
        get 'prices'
      end
    end

    resources :tax_docs, only: [:index, :show] do
      member do
        get 'form_1065'
        get 'schedule_d'
        get 'schedule_k'
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/admin/portfolio_controller.rb
class Admin::PortfolioController < Admin::BaseController
  around_action :skip_bullet, only: :update

  def show
    @position_summaries = PositionSummaryPresenter.all
  end

  def growth
    @portfolio = PortfolioPresenter.all
  end

  def update
    csv_io = params[:csv]
    created = Schwab.process!(csv_io.read)
    if created.present?
      GenerateActivitiesJob.perform_now
    end

    redirect_to action: 'show'
  end

  def transactions
    transactionable = RailsUtil.all(:models).select { |m| m.respond_to?(:as_transactions) }
    @transactions = transactionable
                      .flat_map(&:as_transactions)
                      .sort_by!(&:date)
                      .reverse!
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:csv)
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  self.allow_forgery_protection = false

  def index
    @portfolio = PublicPortfolioPresenter.all(10000)
  end

  def show
    @portfolio = PublicPortfolioPresenter.all(10000)
  end
end

app/views/admin/portfolio/growth.html.haml
%div#growth-wrapper{'data-mutiny-graph' => j(url: growth_admin_portfolio_path(format: 'json'),
                                             xAxis: 'date',
                                             yAxis: 'value',
                                             series: 'name')}

app/views/admin/portfolio/show.html.haml
= form_tag admin_portfolio_path, method: :patch, multipart: true do
  = file_field_tag 'csv'
  %button Upload

%table
  %thead
    %tr
      %th Investment
      %th Opening Date
      %th Opening Price
      %th Current Price
      %th Outstanding Shares
      %th Current Value
      %th{colspan: 2} Unrealized Gain
  - @position_summaries.each do |summary|
    %tbody
      %tr.summary
        %th{rowspan: summary.positions.size+1}= summary.investment.symbol
        %td= summary.opening(:date)
        %td
          - if summary.opening(:adjusted_price)
            = number_to_currency summary.opening(:adjusted_price)
            %small (#{number_to_currency summary.opening(:price)})
        %td= number_to_currency summary.current_price
        %td= summary.outstanding_shares
        %td= number_to_currency summary.current_value
        %td= number_to_currency summary.unrealized_gain
        %td= number_to_percentage 100*summary.unrealized_gain_percent
      - if summary.expandable?
        - summary.positions.each do |position|
          %tr.position
            %td= position.opening(:date)
            %td
              = number_to_currency position.opening(:adjusted_price)
              %small (#{number_to_currency position.opening(:price)})
            %td= number_to_currency position.current_price
            %td= position.outstanding_shares
            %td= number_to_currency position.current_value
            %td= number_to_currency position.unrealized_gain
            %td= number_to_percentage 100*position.unrealized_gain_percent

app/views/admin/portfolio/transactions.html.haml
%table
  %tr
    %th Date
    %th Net Amount
    %th Class
    %th Description
  - @transactions.each do |transaction|
    %tr
      %td= transaction.date
      %td= transaction.net_amount
      %td= transaction.class_name
      %td= transaction.description