config/routes.rb
Rails.application.routes.draw do
  root 'portfolio#index'

  resource :portfolio, controller: :portfolio, only: [:show]

  controller :user do
    get 'summary'
  end

  devise_for :users

  devise_for :admin
  namespace :admin do
    resource :portfolio, controller: :portfolio, only: [:show, :update] do
      member do
        get 'growth'
        get 'transactions'
      end
    end

    resource :summaries, only: [:show] do
      member do
        get 'user/:user_id', action: 'user', as: 'user'
        get 'year/:year',    action: 'year', as: 'year'
      end
    end

    resources :investments, only: [:show] do
      member do
        get 'prices'
      end
    end

    resources :tax_docs, only: [:index, :show] do
      member do
        get 'form_1065'
        get 'schedule_d'
        get 'schedule_k'
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/investment.rb
class Investment < ApplicationRecord
  has_many :historical_prices, class_name: 'InvestmentHistoricalPrice'
  has_many :year_prices, ->{ year_range }, class_name: 'InvestmentHistoricalPrice'
  has_many :dividends,         class_name: 'InvestmentDividend'
  has_many :splits,            class_name: 'InvestmentSplit'

  validates :symbol, presence: true, uniqueness: true
  validates :name,   presence: true

  def self.benchmark
    @benchmark ||= find_by(symbol: 'SPY')
  end

  def self.lookup_by_symbol(&block)
    lookup = Hash.new do |hash, key|
      hash[key] = block.call(key)
    end

    all.each do |investment|
      lookup[investment.symbol] = investment
      investment.past_symbols.each do |symbol|
        lookup[symbol] = investment
      end
    end

    lookup
  end

  def current_price
    year_prices.max_by(&:date).close
  end

  def year_high
    year_prices.map(&:high).max
  end

  def year_low
    year_prices.map(&:low).min
  end

  def self.find_by_param(param)
    find_by(symbol: param)
  end

  def to_param
    symbol
  end

  def to_s
    symbol
  end

  class Stock < Investment
    validates :symbol, format: /\A[A-Z.]{1,4}[^X]?\z/
  end

  class MutualFund < Investment
    validates :symbol, format: /\A[A-Z]{4}X\z/
  end

  class Cash < Investment
    validates :symbol, format: /\A[A-Z]{3}\z/

    def self.default
      @default ||= first
    end

    def current_price
      1
    end

    def year_high
      1
    end

    def year_low
      1
    end
  end

  class Option < Investment
    SYMBOL_FORMAT = /\A(?<root>[A-Z]{1,4})(?<date>[0-9]{6})(?<type>[CP])(?<strike>[0-9]{8})\z/
    validates :symbol, format: SYMBOL_FORMAT

    def underlying_symbol
      symbol_match[:root]
    end

    def expiration_date
      Date.strptime(symbol_match[:date], '%y%m%d')
    end

    def put?
      symbol_match[:type] == 'P'
    end

    def call?
      symbol_match[:type] == 'C'
    end

    def strike_price
      Rational(symbol_match[:strike], 1000)
    end

    def symbol_match
      SYMBOL_FORMAT.match(symbol)
    end
  end
end

app/controllers/admin/investments_controller.rb
class Admin
  class InvestmentsController < BaseController
    before_action :set_investment

    def show
    end

    def prices
      end_date = params[:end_date] ? Date.parse(params[:end_date]) : Date.current
      start_date = params[:start_date] ? Date.parse(params[:start_date]) : end_date - 365

      @prices = InvestmentHistoricalPrice.where(investment: @investment, date: start_date..end_date).order('date')
      @prices = InvestmentHistoricalPricePresenter.wrap_all(@prices)

      respond_to do |format|
        format.html
        format.json
      end
    end

    private
    def set_investment
      @investment = Investment.find_by_param(params[:id])
    end
  end
end

app/views/admin/investments/prices.html.haml
%table
  %thead
    %tr
      %th Date
      %th High
      %th Low
      %th Close
      %th Adjusted Close
  %tbody
    - @prices.each do |price|
      %tr
        %th= price.date
        %td= number_to_currency price.high
        %td= number_to_currency price.low
        %td= number_to_currency price.close
        %td= number_to_currency price.adjusted(:close)
        %td= price.misc

app/views/admin/investments/show.html.haml
%dl
  %dt Symbol
  %dd= @investment.symbol

  %dt Name
  %dd= @investment.name

  %dt 52 week price
  %dd #{number_to_currency @investment.year_low} - #{number_to_currency @investment.year_high}

  %dt Price
  %dd
    = link_to 'table', prices_admin_investment_path(@investment)
    %div#price-wrapper{'data-mutiny-graph' => j(url:   prices_admin_investment_path(@investment, format: 'json'),
                                                xAxis: 'date',
                                                yAxis: 'adjusted_close')}